#  파이썬을 활용한딥러닝
# 7강. 파이썬 NumPy #3

## 1. NumPy 배열 재형성

### reshape
- NumPy에서 배열의 차원을 재구조화, 변경하고자 할 때 사용
- 요소의 개수는 동일해야 한다. 

In [1]:
import numpy as np

In [2]:
t_array = np.arange(1,9)
t_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
t_array.shape

(8,)

In [4]:
a = t_array.reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a.shape

(2, 4)

In [7]:
a.reshape(-1,2).shape # -1은 요소의 개수에 따라 산정된다.

(4, 2)

### 평탄화
- 다차원 배열을 낮은차원으로 변환

#### ravel
- 다차원 배열을 낮은 차원으로 변환
- ravel은 원본의 뷰를 반환하기 때문에 ravel로 반환된 데이터
   를 수정하면 원본 데이터도 수정 된다.

In [23]:
b = np.array([ [[1, 2], [3, 4]], [[1, 2], [3, 4]] ])
b

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [15]:
c = b.ravel()
c

array([1, 2, 3, 4, 1, 2, 3, 4])

In [19]:
c[3] = 0
c

array([1, 2, 3, 0, 1, 2, 3, 4])

In [20]:
b

array([[[1, 2],
        [3, 0]],

       [[1, 2],
        [3, 4]]])

#### flatten
- 다차원 배열을 낮은 차원으로 변환
- flatten 원본의 복사본을 반환한다
- flatten은 flatten으로 반환된 데이터를 수정하여도 원본데이터는 변하지 않는다.

In [25]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [26]:
c = b.flatten()
c

array([1, 2, 3, 4])

In [27]:
c[3] = 0
c

array([1, 2, 3, 0])

In [28]:
b

array([[1, 2],
       [3, 4]])

### 전치 – transpose
 - 행렬의 인덱스가 바뀌는 변환
 - transpose 또는 T 속성을 사용한다.

In [35]:
a = np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [31]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

### 배열결합 – concatenate
 - 배열과 배열을 결합하는 함수
 - axis 기준으로 결합

In [32]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a = np.array([ [1, 2], [3, 4] ])
b = np.array([ [5, 6] ])
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

## 2. NumPy 색인

### 색인 (indexing)
- 배열의 각 요소는 axis 인덱스 배열로 참조 할 수 있다.
- 1차원 배열은 1개의 인덱스, 2차원 배열은 2개의 인덱스,
     n차원 배열은 n개의 인덱스로 요소를 참조 할 수 있다.


In [36]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [37]:
print("a의 0번째 요소 = ", a[0])  
print("a의 1번째 요소 = ", a[1])  

a의 0번째 요소 =  1
a의 1번째 요소 =  2


In [38]:
b = a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [40]:
print(b[0, 0])  
print(b[1][1]) 

1
4


- 할당

In [41]:
b[0, 0] = 7   
print(b)

[[7 2]
 [3 4]]


In [42]:
b[1][0] = 8   
print(b)

[[7 2]
 [8 4]]


### 슬라이스 색인
- 여러 개의 배열 요소를 참조할 때 슬라이싱을 사용한다. 
- 다차원 객체는 하나 이상의 축(axis)을 기준으로 슬라이싱 한다.

In [43]:
a1 = np.arange(1, 21).reshape((4, 5)) #2차원 배열
print(a1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
a1[:, 1:]   # 전체 row의 1열 이상

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [45]:
a1[2, 1:4]  # 1 row의 2열~3열

array([12, 13, 14])

In [46]:
a1[2:7]  # 2 row ~ 로우 전체 

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

- step을 활용한 슬라이싱

In [47]:
a1[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [48]:
a1[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

### boolean indexing
- 배열 각 요소에 조건에 대한 값을 True, False로 지정한 후,
   해당 index의 True값만 추출하는 방법

In [52]:
a = np.arange(1, 21).reshape(4, 5) #2차원 배열
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [53]:
bool_a = a%2==0  # 몫의 나머지 = 0 일경우 true
print(bool_a)

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]


In [54]:
a[bool_a]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [57]:
b = np.logical_and(a > 10 , a < 17)
b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False]])

In [58]:
a[b]

array([11, 12, 13, 14, 15, 16])

### fancy indexing
- 정수 배열을 사용한 색인을 설명하기 위해 NumPy에서 차용한 
   단어이다.
- ndarray를 index value로 사용하여 값을 추출한다.

**1차원**

In [59]:
array_a = np.arange(1,7)
array_b = np.array( [1, 0, 2, 0, 1, 4], int )  # 반드시 integer로 선언
array_a[array_b]  # bracket index, b 배열의 값을 index로 하여 a의 값 추출

array([2, 1, 3, 1, 2, 5])

In [60]:
array_a.take(array_b)

array([2, 1, 3, 1, 2, 5])

**2차원**

In [61]:
array_a = np.arange(1,7).reshape(2,3)
array_b = np.array( [1, 0, 1, 0, 1], int ) 
array_c = np.array( [1, 1, 0, 0, 2], int ) 
array_a[array_b,array_c]

array([5, 2, 4, 1, 6])

## 3. NumPy i/o

### loadtxt, savetxt
 - 텍스트 파일을 불러오고 저장하는 방법

#### save

In [62]:
a = np.arange(1, 200, 2).reshape(20, 5)
a

array([[  1,   3,   5,   7,   9],
       [ 11,  13,  15,  17,  19],
       [ 21,  23,  25,  27,  29],
       [ 31,  33,  35,  37,  39],
       [ 41,  43,  45,  47,  49],
       [ 51,  53,  55,  57,  59],
       [ 61,  63,  65,  67,  69],
       [ 71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89],
       [ 91,  93,  95,  97,  99],
       [101, 103, 105, 107, 109],
       [111, 113, 115, 117, 119],
       [121, 123, 125, 127, 129],
       [131, 133, 135, 137, 139],
       [141, 143, 145, 147, 149],
       [151, 153, 155, 157, 159],
       [161, 163, 165, 167, 169],
       [171, 173, 175, 177, 179],
       [181, 183, 185, 187, 189],
       [191, 193, 195, 197, 199]])

In [63]:
np.savetxt( "int_price_1.csv" , a, delimiter = "," )

In [64]:
np.savetxt( "int_price_2.csv" , a, fmt = '%d', delimiter = "," )

#### load

In [66]:
b = np.loadtxt( "./int_price_2.csv", delimiter = ","  )
b[:5]  # python 기본타입 float 형태로 보임

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [41., 43., 45., 47., 49.]])

In [67]:
b_int = b.astype(int)
b_int[:3]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

#### npy
- Numpy object (pickle) 형태로 데이터를 저장하고 불러옴
- Binary 형태로 파일 저장

In [68]:
np.save( "npy_test" , arr = b_int )

In [69]:
npy_array = np.load( file = "npy_test.npy")
npy_array[:3]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])